src/Entity/Sav.php
<?php

namespace App\Entity;

use App\Repository\SavRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SavRepository::class)
 */
class Sav
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $sav_nom;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $sav_prenom;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $sav_adr1;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $sav_adr2;

    /**
     * @ORM\Column(type="string", length=5)
     */
    private $sav_codepos;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $sav_ville;

    /**
     * @ORM\Column(type="text")
     */
    private $sav_probleme;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dt_crea;

    /**
     * @ORM\ManyToMany(targetEntity=Client::class, mappedBy="sav")
     */
    private $clients;

    public function __construct()
    {
        $this->client = new ArrayCollection();
        $this->clients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSavNom(): ?string
    {
        return $this->sav_nom;
    }

    public function setSavNom(string $sav_nom): self
    {
        $this->sav_nom = $sav_nom;

        return $this;
    }

    public function getSavPrenom(): ?string
    {
        return $this->sav_prenom;
    }

    public function setSavPrenom(?string $sav_prenom): self
    {
        $this->sav_prenom = $sav_prenom;

        return $this;
    }

    public function getSavAdr1(): ?string
    {
        return $this->sav_adr1;
    }

    public function setSavAdr1(string $sav_adr1): self
    {
        $this->sav_adr1 = $sav_adr1;

        return $this;
    }

    public function getSavAdr2(): ?string
    {
        return $this->sav_adr2;
    }

    public function setSavAdr2(?string $sav_adr2): self
    {
        $this->sav_adr2 = $sav_adr2;

        return $this;
    }

    public function getSavCodepos(): ?string
    {
        return $this->sav_codepos;
    }

    public function setSavCodepos(string $sav_codepos): self
    {
        $this->sav_codepos = $sav_codepos;

        return $this;
    }

    public function getSavVille(): ?string
    {
        return $this->sav_ville;
    }

    public function setSavVille(string $sav_ville): self
    {
        $this->sav_ville = $sav_ville;

        return $this;
    }

    public function getSavProbleme(): ?string
    {
        return $this->sav_probleme;
    }

    public function setSavProbleme(string $sav_probleme): self
    {
        $this->sav_probleme = $sav_probleme;

        return $this;
    }

    public function getDtCrea(): ?\DateTimeInterface
    {
        return $this->dt_crea;
    }

    public function setDtCrea(\DateTimeInterface $dt_crea): self
    {
        $this->dt_crea = $dt_crea;

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getClients(): Collection
    {
        return $this->clients;
    }

    public function addClient(Client $client): self
    {
        if (!$this->clients->contains($client)) {
            $this->clients[] = $client;
            $client->addSav($this);
        }

        return $this;
    }

    public function removeClient(Client $client): self
    {
        if ($this->clients->removeElement($client)) {
            $client->removeSav($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getSavNom();
    }
}

src/Form/SavType.php
<?php

namespace App\Form;

use App\Entity\Sav;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SavType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('sav_nom')
            ->add('sav_prenom')
            ->add('sav_adr1')
            ->add('sav_adr2')
            ->add('sav_codepos')
            ->add('sav_ville')
            ->add('sav_probleme')
            ->add('clients')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Sav::class,
        ]);
    }
}

src/Controller/SavController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Sav;
use App\Form\SavType;
use App\Repository\SavRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/sav")
 */
class SavController extends AbstractController
{
    /**
     * @Route("/", name="sav_index", methods={"GET"})
     */
    public function index(SavRepository $savRepository): Response
    {
        return $this->render('sav/index.html.twig', [
            'savs' => $savRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="sav_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $sav = new Sav();
        $sav->setDtCrea(new \DateTime());
        $id_client = $request->get('id_client');
        if (!empty($id_client)) {
            $client = $this->getDoctrine()
                ->getRepository(Client::class)
                ->find($id_client);
            $sav->setSavNom($client->getNom());
            $sav->setSavPrenom($client->getPrenom());
            $sav->setSavAdr1($client->getAdr1());
            $sav->setSavAdr2($client->getAdr2());
            $sav->setSavCodepos($client->getCodepos());
            $sav->setSavVille($client->getVille());
        }
        $form = $this->createForm(SavType::class, $sav);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $sav->setDtCrea(new \DateTime());
            $entityManager->persist($sav);
            $entityManager->flush();

            return $this->redirectToRoute('sav_index');
        }

        return $this->render('sav/new.html.twig', [
            'sav' => $sav,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sav_show", methods={"GET"})
     */
    public function show(Sav $sav): Response
    {
        return $this->render('sav/show.html.twig', [
            'sav' => $sav,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="sav_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Sav $sav): Response
    {
        $form = $this->createForm(SavType::class, $sav);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('sav_index');
        }

        return $this->render('sav/edit.html.twig', [
            'sav' => $sav,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="sav_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Sav $sav): Response
    {
        if ($this->isCsrfTokenValid('delete' . $sav->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($sav);
            $entityManager->flush();
        }

        return $this->redirectToRoute('sav_index');
    }
}

templates/sav/_delete_form.html.twig
<form method="post" action="{{ path('sav_delete', {'id': sav.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ sav.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/sav/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/sav/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Sav{% endblock %}

{% block body %}
    <h1>Edit Sav</h1>

    {{ include('sav/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('sav_index') }}">{% trans %}retour à la liste{% endtrans %}</a>

    {{ include('sav/_delete_form.html.twig') }}
{% endblock %}

templates/sav/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sav index{% endblock %}

{% block body %}
    <h1>Sav index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Sav_nom</th>
                <th>Sav_prenom</th>
                <th>Sav_adr1</th>
                <th>Sav_adr2</th>
                <th>Sav_codepos</th>
                <th>Sav_ville</th>
                <th>Sav_probleme</th>
                <th>Dt_crea</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for sav in savs %}
            <tr>
                <td>{{ sav.id }}</td>
                <td>{{ sav.savNom }}</td>
                <td>{{ sav.savPrenom }}</td>
                <td>{{ sav.savAdr1 }}</td>
                <td>{{ sav.savAdr2 }}</td>
                <td>{{ sav.savCodepos }}</td>
                <td>{{ sav.savVille }}</td>
                <td>{{ sav.savProbleme }}</td>
                <td>{{ sav.dtCrea ? sav.dtCrea|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('sav_show', {'id': sav.id}) }}">{% trans %}voir{% endtrans %}</a>
                    <a href="{{ path('sav_edit', {'id': sav.id}) }}">{% trans %}modifier{% endtrans %}</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('sav_new') }}">{% trans %}Create new{% endtrans %}</a>
{% endblock %}

templates/sav/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Sav{% endblock %}

{% block body %}
    <h1>{% trans %}Create new{% endtrans %} Sav</h1>

    {{ include('sav/_form.html.twig') }}

    <a href="{{ path('sav_index') }}">{% trans %}retour à la liste{% endtrans %}</a>
{% endblock %}

templates/sav/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sav{% endblock %}

{% block body %}
    <h1>Sav</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ sav.id }}</td>
            </tr>
            <tr>
                <th>Sav_nom</th>
                <td>{{ sav.savNom }}</td>
            </tr>
            <tr>
                <th>Sav_prenom</th>
                <td>{{ sav.savPrenom }}</td>
            </tr>
            <tr>
                <th>Sav_adr1</th>
                <td>{{ sav.savAdr1 }}</td>
            </tr>
            <tr>
                <th>Sav_adr2</th>
                <td>{{ sav.savAdr2 }}</td>
            </tr>
            <tr>
                <th>Sav_codepos</th>
                <td>{{ sav.savCodepos }}</td>
            </tr>
            <tr>
                <th>Sav_ville</th>
                <td>{{ sav.savVille }}</td>
            </tr>
            <tr>
                <th>Sav_probleme</th>
                <td>{{ sav.savProbleme }}</td>
            </tr>
            <tr>
                <th>Dt_crea</th>
                <td>{{ sav.dtCrea ? sav.dtCrea|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('sav_index') }}">{% trans %}retour à la liste{% endtrans %}</a>

    <a href="{{ path('sav_edit', {'id': sav.id}) }}">edit</a>

    {{ include('sav/_delete_form.html.twig') }}
{% endblock %}